### ISSUE TITLE
Backport RK3588 eMMC HS400 fix

### ISSUE THREAD

**Issue by RadxaYuntian** [radxa/kernel#254]
https://patchwork.kernel.org/project/linux-rockchip/patch/20231205202900.4617-2-CFSworks@gmail.com/

**Comment by RadxaStephen** [comment]
I added it to branch linux-6.1-stan-rkr1 already. https://github.com/radxa/kernel/commit/07337b18d099709f4f0443bd18022c4cd75b1a8c
