### ISSUE TITLE
Bug in Mali GPU driver? NULL pointer dereference when only one regulator

### ISSUE THREAD

**Issue by TaihuLight** [radxa/kernel#45]
@finley1226  @Zhen Chen  @rkhuangtao Does the official kernel [linux-5.10-gen-rkr3.4](https://github.com/radxa/kernel) branch also suffers from the bug show in 
[MALI: bifrost: Add memory regulator support](https://github.com/Fruit-Pi/kernel/commit/08c244de34db4f85da0b1141b83131ec76ff5b5e)?

```
MALI: bifrost: Fix NULL pointer dereference when only one regulator
Unable to handle kernel NULL pointer dereference at virtual address 0000000000000078
Mem abort info:
  ESR = 0x96000005
  EC = 0x25: DABT (current EL), IL = 32 bits
  SET = 0, FnV = 0
  EA = 0, S1PTW = 0
Data abort info:
  ISV = 0, ISS = 0x00000005
  CM = 0, WnR = 0
[0000000000000078] user address but active_mm is swapper
Internal error: Oops: 96000005 [https://github.com/Fruit-Pi/kernel/issues/1] PREEMPT SMP
```

**Comment by RadxaYuntian** [comment]
Seems the code was already patched: https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr3.4/drivers/gpu/arm/bifrost/backend/gpu/mali_kbase_devfreq.c#L130
