### ISSUE TITLE
Hardware Cursor Disappearing 

### ISSUE THREAD

**Issue by efectn** [radxa/kernel#57]
Cursor is disappearing after turning off & turning on the monitor. Problem is exists on RK3588 and RK3588S, looks like general problem.

https://forum.radxa.com/t/flickering-cursor/13398/24
https://forum.armbian.com/topic/25600-wip-current-issues/?do=findComment&comment=157821

**Comment by martivo** [comment]
Has happened to me too on few occasions when changing the resolution of the display on RK3588S chipset. Changing it again can bring it back. The pointer seems to be still working, but not visible since hovering over buttons causes them to change color.
