### ISSUE TITLE
No overlay file (dts) found for SPI2 on Rock4 boards

### ISSUE THREAD

**Issue by Gerriko** [radxa/kernel#75]
I refer to: https://github.com/radxa/kernel/tree/linux-5.10-gen-rkr3.4/arch/arm64/boot/dts/rockchip/overlay

I can only find dts files for spi0, which is attached to the Ethernet module on Rock4 boards, and spi1, which is available.

There is no dts file for spi2.

**Comment by RadxaYuntian** [comment]
We moved the in-tree overlays into a separate repository to facilitate separate development. We plan to remove in-tree overlays in the future.

You can find DTS for SPI2 [here](https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3399-spi2-spidev.dts).
